services:
    common:
        build: ./common
        volumes:
            - common:/usr/src/common

    gateway:
        build: ./gateway
        ports:
            - 127.0.0.1:8080:8080
        depends_on:
            - common
            - server
        volumes:
            - common:/usr/src/common
        networks:
            - server_network

    server:
        build: ./server
        ports:
            - 127.0.0.1:3000:3000
        depends_on:
            common:
                condition: service_started
            db:
                condition: service_healthy
        volumes:
            - common:/usr/src/common
        networks:
            - db_network
            - server_network

    db:
        image: mysql:8.0
        ports:
            - 3307:3306
        networks:
            - db_network
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: cms
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 10

volumes:
    common:
    mysql-data:

networks:
    db_network:
    server_network:
